# Patches validator generated by https://github.com/ForbesLindesay/typescript-json-validator to work in browser env
sed -i '' '1s;^;import metaSchema from "ajv\/lib\/refs\/json-schema-draft-06.json"\n;' src/facedata.d.validator.ts
sed -i '' '/ajv.addMetaSchema/c\
ajv.addMetaSchema(metaSchema)
' src/facedata.d.validator.ts
