/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { EmotionSet } from "./core";
import { SliderChangedEvent } from "./components/slider/slider";
export namespace Components {
    interface GrimaceCanvas {
        "emotions": EmotionSet;
        "isServer": boolean;
    }
    interface GrimaceContainer {
        "emotionSet": EmotionSet;
    }
    interface GrimaceSlider {
        "label": string;
        "name": string;
        "value": number;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLGrimaceCanvasElement extends Components.GrimaceCanvas, HTMLStencilElement {
    }
    var HTMLGrimaceCanvasElement: {
        prototype: HTMLGrimaceCanvasElement;
        new (): HTMLGrimaceCanvasElement;
    };
    interface HTMLGrimaceContainerElement extends Components.GrimaceContainer, HTMLStencilElement {
    }
    var HTMLGrimaceContainerElement: {
        prototype: HTMLGrimaceContainerElement;
        new (): HTMLGrimaceContainerElement;
    };
    interface HTMLGrimaceSliderElement extends Components.GrimaceSlider, HTMLStencilElement {
    }
    var HTMLGrimaceSliderElement: {
        prototype: HTMLGrimaceSliderElement;
        new (): HTMLGrimaceSliderElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "grimace-canvas": HTMLGrimaceCanvasElement;
        "grimace-container": HTMLGrimaceContainerElement;
        "grimace-slider": HTMLGrimaceSliderElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface GrimaceCanvas {
        "emotions"?: EmotionSet;
        "isServer"?: boolean;
    }
    interface GrimaceContainer {
        "emotionSet"?: EmotionSet;
        "onGrimace:setEmotionSet"?: (event: CustomEvent<EmotionSet>) => void;
        "onGrimace:setRandomEmotionSet"?: (event: CustomEvent<any>) => void;
    }
    interface GrimaceSlider {
        "label"?: string;
        "name"?: string;
        "onSliderValueChanged"?: (event: CustomEvent<SliderChangedEvent>) => void;
        "value"?: number;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "grimace-canvas": GrimaceCanvas;
        "grimace-container": GrimaceContainer;
        "grimace-slider": GrimaceSlider;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "grimace-canvas": LocalJSX.GrimaceCanvas & JSXBase.HTMLAttributes<HTMLGrimaceCanvasElement>;
            "grimace-container": LocalJSX.GrimaceContainer & JSXBase.HTMLAttributes<HTMLGrimaceContainerElement>;
            "grimace-slider": LocalJSX.GrimaceSlider & JSXBase.HTMLAttributes<HTMLGrimaceSliderElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
